// Code generated by go-swagger; DO NOT EDIT.

package rolebinding

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddRoleBindingHandlerFunc turns a function with the right signature into a add role binding handler
type AddRoleBindingHandlerFunc func(AddRoleBindingParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddRoleBindingHandlerFunc) Handle(params AddRoleBindingParams) middleware.Responder {
	return fn(params)
}

// AddRoleBindingHandler interface for that can handle valid add role binding params
type AddRoleBindingHandler interface {
	Handle(AddRoleBindingParams) middleware.Responder
}

// NewAddRoleBinding creates a new http.Handler for the add role binding operation
func NewAddRoleBinding(ctx *middleware.Context, handler AddRoleBindingHandler) *AddRoleBinding {
	return &AddRoleBinding{Context: ctx, Handler: handler}
}

/*
	AddRoleBinding swagger:route POST /rolebindings rolebinding addRoleBinding

AddRoleBinding add role binding API
*/
type AddRoleBinding struct {
	Context *middleware.Context
	Handler AddRoleBindingHandler
}

func (o *AddRoleBinding) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddRoleBindingParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
