// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"open-cluster-management.io/grc-rbac-policy-api/models"
)

// CheckAccessOKCode is the HTTP code returned for type CheckAccessOK
const CheckAccessOKCode int = 200

/*
CheckAccessOK list the fine grained RBAC access

swagger:response checkAccessOK
*/
type CheckAccessOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewCheckAccessOK creates CheckAccessOK with default headers values
func NewCheckAccessOK() *CheckAccessOK {

	return &CheckAccessOK{}
}

// WithPayload adds the payload to the check access o k response
func (o *CheckAccessOK) WithPayload(payload []*models.Item) *CheckAccessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check access o k response
func (o *CheckAccessOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckAccessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
CheckAccessDefault generic error response

swagger:response checkAccessDefault
*/
type CheckAccessDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCheckAccessDefault creates CheckAccessDefault with default headers values
func NewCheckAccessDefault(code int) *CheckAccessDefault {
	if code <= 0 {
		code = 500
	}

	return &CheckAccessDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the check access default response
func (o *CheckAccessDefault) WithStatusCode(code int) *CheckAccessDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the check access default response
func (o *CheckAccessDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the check access default response
func (o *CheckAccessDefault) WithPayload(payload *models.Error) *CheckAccessDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check access default response
func (o *CheckAccessDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckAccessDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
