// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"open-cluster-management.io/grc-rbac-policy-api/models"
)

// DeleteAccessOKCode is the HTTP code returned for type DeleteAccessOK
const DeleteAccessOKCode int = 200

/*
DeleteAccessOK deleted the resources for a policy

swagger:response deleteAccessOK
*/
type DeleteAccessOK struct {
}

// NewDeleteAccessOK creates DeleteAccessOK with default headers values
func NewDeleteAccessOK() *DeleteAccessOK {

	return &DeleteAccessOK{}
}

// WriteResponse to the client
func (o *DeleteAccessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
DeleteAccessDefault generic error response

swagger:response deleteAccessDefault
*/
type DeleteAccessDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAccessDefault creates DeleteAccessDefault with default headers values
func NewDeleteAccessDefault(code int) *DeleteAccessDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteAccessDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete access default response
func (o *DeleteAccessDefault) WithStatusCode(code int) *DeleteAccessDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete access default response
func (o *DeleteAccessDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete access default response
func (o *DeleteAccessDefault) WithPayload(payload *models.Error) *DeleteAccessDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete access default response
func (o *DeleteAccessDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAccessDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
