// Code generated by go-swagger; DO NOT EDIT.

// Package restapi MultiCluster Fine Grained RBAC
//
//	Query Kubernetes RBAC RoleBindings from the Policy Administration Point
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/io.open-cluster-management.rbac.access-list.v1+json
//
//	Produces:
//	  - application/io.open-cluster-management.rbac.access-list.v1+json
//
// swagger:meta
package restapi
