// Code generated by go-swagger; DO NOT EDIT.

package rolebindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"open-cluster-management.io/grc-rbac-policy-api/models"
)

// GetRoleBindingsOKCode is the HTTP code returned for type GetRoleBindingsOK
const GetRoleBindingsOKCode int = 200

/*
GetRoleBindingsOK retrieve the full cache of role bindings

swagger:response getRoleBindingsOK
*/
type GetRoleBindingsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ACL `json:"body,omitempty"`
}

// NewGetRoleBindingsOK creates GetRoleBindingsOK with default headers values
func NewGetRoleBindingsOK() *GetRoleBindingsOK {

	return &GetRoleBindingsOK{}
}

// WithPayload adds the payload to the get role bindings o k response
func (o *GetRoleBindingsOK) WithPayload(payload []*models.ACL) *GetRoleBindingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get role bindings o k response
func (o *GetRoleBindingsOK) SetPayload(payload []*models.ACL) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRoleBindingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ACL, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetRoleBindingsDefault generic error response

swagger:response getRoleBindingsDefault
*/
type GetRoleBindingsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRoleBindingsDefault creates GetRoleBindingsDefault with default headers values
func NewGetRoleBindingsDefault(code int) *GetRoleBindingsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRoleBindingsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get role bindings default response
func (o *GetRoleBindingsDefault) WithStatusCode(code int) *GetRoleBindingsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get role bindings default response
func (o *GetRoleBindingsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get role bindings default response
func (o *GetRoleBindingsDefault) WithPayload(payload *models.Error) *GetRoleBindingsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get role bindings default response
func (o *GetRoleBindingsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRoleBindingsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
